# Generated by Django 4.2.1 on 2023-05-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Email', models.CharField(max_length=64)),
                ('Age', models.IntegerField()),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
