# Generated by Django 4.2.1 on 2023-05-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_name_employee_jobtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='none', max_length=100)),
                ('password', models.CharField(default='none', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='ID',
            field=models.BigAutoField(default=20230000, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
