# Generated by Django 4.2.1 on 2023-05-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_hr_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ID',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
