# Generated by Django 3.0.14 on 2023-05-24 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230524_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('EmployeeID', models.IntegerField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Employee', verbose_name='Employee ID'))),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.TextField(default='Pending', max_length=20)),
            ],
        ),
    ]
