# Generated by Django 3.0.14 on 2023-05-24 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_vacation'),
        ('main', '0007_alter_hr_id'),
    ]

    operations = [
    ]
