# Generated by Django 3.0.14 on 2023-05-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_merge_20230525_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
