# Generated by Django 4.2.1 on 2023-05-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20230525_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
