# Generated by Django 4.2.1 on 2023-05-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_hr_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='Manager', max_length=100)),
                ('password', models.CharField(default='admin', max_length=100)),
            ],
        ),
    ]
