# Generated by Django 3.0.14 on 2023-06-01 15:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_vacation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hr',
            name='id',
        ),
        migrations.AddField(
            model_name='hr',
            name='Email',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hr',
            name='ID',
            field=models.BigAutoField( primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hr',
            name='address',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hr',
            name='birthDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hr',
            name='gender',
            field=models.CharField(default='none', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hr',
            name='maritalStatus',
            field=models.CharField(default='none', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hr',
            name='phoneNum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hr',
            name='vacationDays',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hr',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hr',
            name='userName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='EmployeeID',
            field=models.IntegerField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employee ID', to='main.Employee', verbose_name='Employee ID')),
        ),
    ]
